### ISSUE TITLE
visualize.py error

### ISSUE THREAD

**Issue by dubrovin-sudo** [bebeal/mipnerf-pytorch#7]
Try to render a video from the trained model, but got error @bebeal @ninaahmed 

Full log after visualize.py implementation

> /home/trillion/miniconda3/envs/mipNeRF/bin/python visualize.py 
> Generating Render Poses
> Generating rays
> Done
> 
> Generating Video using 120 different view points
> 100%|██████████| 120/120 [57:49<00:00, 28.92s/it]
> Traceback (most recent call last):
>   File "visualize.py", line 59, in <module>
>     visualize(config)
>   File "visualize.py", line 50, in visualize
>     imageio.mimwrite(path.join(config.log_dir, "video.mp4"), rgb_frames, fps=30, quality=10, codecs="hvec")
>   File "/home/trillion/miniconda3/envs/mipNeRF/lib/python3.7/site-packages/imageio/v2.py", line 331, in mimwrite
>     return file.write(ims, **kwargs)
>   File "/home/trillion/miniconda3/envs/mipNeRF/lib/python3.7/site-packages/imageio/core/legacy_plugin_wrapper.py", line 182, in write
>     with self.legacy_get_writer(**kwargs) as writer:
>   File "/home/trillion/miniconda3/envs/mipNeRF/lib/python3.7/site-packages/imageio/core/legacy_plugin_wrapper.py", line 163, in legacy_get_writer
>     return self._format.get_writer(self._request)
>   File "/home/trillion/miniconda3/envs/mipNeRF/lib/python3.7/site-packages/imageio/core/format.py", line 234, in get_writer
>     return self.Writer(self, request)
>   File "/home/trillion/miniconda3/envs/mipNeRF/lib/python3.7/site-packages/imageio/core/format.py", line 311, in __init__
>     self._open(**self.request.kwargs.copy())
> TypeError: _open() got an unexpected keyword argument 'codecs'

What I gotta do with codecs?

**Comment by DrawingProcess** [comment]
I got a same issue. Did you solve it?

**Comment by DrawingProcess** [comment]
Solved it! Modify visualize.py as shown below.
```
    imageio.mimwrite(path.join(config.log_dir, "video.mp4"), rgb_frames, fps=30, quality=5, codec="h264")
    if config.visualize_depth:
        imageio.mimwrite(path.join(config.log_dir, "depth.mp4"), depth_frames, fps=30, quality=5, codec="h264")
    if config.visualize_normals:
        imageio.mimwrite(path.join(config.log_dir, "normals.mp4"), normal_frames, fps=30, quality=5, codec="h264")
```
